

services:

  backend:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: dotnet_api
    working_dir: /app
    volumes:
      - ./backend:/app
    command: >
      sh -c "dotnet restore &&
             dotnet run --urls http://0.0.0.0:8080"
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ConnectionStrings__DefaultConnection: "server=db;port=3306;database=project_tasks;user=sadki;password=13456"
    depends_on:
      - db

  frontend:
    image: node:20
    container_name: react_app
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: >
      sh -c "npm install &&
             npm run dev -- --host"
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://localhost:8080"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_tasks
      MYSQL_USER: sadki
      MYSQL_PASSWORD: 13456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
